import streamlit as st
import time
import pandas as pd
import numpy as np
import subprocess
import sys
import psutil
import json
import io
from datetime import datetime, timedelta
from pathlib import Path
from engine.simulation import generate_patient_data
from engine.predict_model import load_trained_model, predict_psychosis
from sklearn.preprocessing import MinMaxScaler

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False

# Path to shared alert status file
STATUS_FILE = Path(__file__).parent / "alert_status.json"

# --- PDF CLINICAL REPORT GENERATION ---
class ClinicalReportPDF(FPDF):
    """Professional Clinical Report PDF Generator"""
    
    def __init__(self):
        super().__init__('P', 'mm', 'A4')
        self.accent_color = (0, 173, 181)  # Teal accent
        self.header_gray = (60, 60, 60)
        self.text_color = (30, 30, 30)
        self.light_gray = (180, 180, 180)
        
    def header(self):
        # ICU Guardian Logo/Title
        self.set_font('Helvetica', 'B', 18)
        self.set_text_color(*self.accent_color)
        self.cell(100, 10, 'ICU GUARDIAN', 0, 0, 'L')
        
        # Timestamp on right
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*self.header_gray)
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
        self.cell(0, 10, f'Generated: {timestamp}', 0, 1, 'R')
        
        # Sub-header
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(*self.light_gray)
        self.cell(0, 6, 'Confidential Clinical Summary | Neuro-Trauma Unit', 0, 1, 'L')
        
        # Separator line
        self.set_draw_color(*self.accent_color)
        self.set_line_width(0.5)
        self.line(10, 28, 200, 28)
        self.ln(10)
        
    def footer(self):
        self.set_y(-35)
        
        # Signature line
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*self.text_color)
        self.cell(130, 6, '', 0, 0)
        self.cell(0, 6, '__________________________', 0, 1, 'R')
        self.cell(130, 5, '', 0, 0)
        self.set_font('Helvetica', 'I', 9)
        self.set_text_color(*self.header_gray)
        self.cell(0, 5, 'Attending Physician / MD', 0, 1, 'R')
        
        # Legal disclaimer
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*self.light_gray)
        self.cell(0, 5, 'Generated by ICU Guardian Clinical AI System. Not for legal diagnostic use.', 0, 1, 'C')
        
    def section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(*self.header_gray)
        self.set_fill_color(245, 245, 245)
        self.cell(0, 8, title, 0, 1, 'L', True)
        self.ln(3)
        
    def add_vitals_table(self, vitals_data):
        self.section_title('PATIENT VITALS SNAPSHOT')
        
        # Table header
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(255, 255, 255)
        self.set_fill_color(*self.header_gray)
        col_widths = [50, 45, 50, 45]
        headers = ['Parameter', 'Value', 'Parameter', 'Value']
        
        for i, (header, width) in enumerate(zip(headers, col_widths)):
            self.cell(width, 8, header, 1, 0, 'C', True)
        self.ln()
        
        # Table data
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*self.text_color)
        self.set_fill_color(255, 255, 255)
        
        # Row 1: HR and SpO2
        self.cell(col_widths[0], 8, 'Average Heart Rate', 1, 0, 'L')
        self.cell(col_widths[1], 8, f"{vitals_data.get('hr', '--')} BPM", 1, 0, 'C')
        self.cell(col_widths[2], 8, 'Minimum SpO2', 1, 0, 'L')
        self.cell(col_widths[3], 8, f"{vitals_data.get('spo2', '--')}%", 1, 1, 'C')
        
        # Row 2: RASS and Risk
        self.cell(col_widths[0], 8, 'RASS Score', 1, 0, 'L')
        self.cell(col_widths[1], 8, str(vitals_data.get('rass', '--')), 1, 0, 'C')
        self.cell(col_widths[2], 8, 'AI Risk Probability', 1, 0, 'L')
        
        # Color code risk
        risk = vitals_data.get('risk', 0)
        if risk > 0.6:
            self.set_text_color(220, 53, 69)  # Red
        elif risk > 0.4:
            self.set_text_color(255, 152, 0)  # Orange
        else:
            self.set_text_color(40, 167, 69)  # Green
        self.cell(col_widths[3], 8, f"{risk:.0%}", 1, 1, 'C')
        self.set_text_color(*self.text_color)
        
        self.ln(5)
        
    def add_vitals_graph(self, hr_data, spo2_data):
        self.section_title('PHYSIOLOGICAL TREND ANALYSIS (Last 30 mins)')
        
        # Graph dimensions
        graph_x = 15
        graph_y = self.get_y() + 5
        graph_width = 180
        graph_height = 50
        
        # Draw graph background
        self.set_fill_color(250, 250, 250)
        self.set_draw_color(200, 200, 200)
        self.rect(graph_x, graph_y, graph_width, graph_height, 'DF')
        
        # Draw grid lines
        self.set_draw_color(230, 230, 230)
        for i in range(1, 5):
            y_line = graph_y + (graph_height / 5) * i
            self.line(graph_x, y_line, graph_x + graph_width, y_line)
        
        # Normalize data for plotting
        if len(hr_data) >= 2:
            hr_min, hr_max = min(hr_data), max(hr_data)
            if hr_max == hr_min:
                hr_max = hr_min + 1
            
            # Draw HR line (teal)
            self.set_draw_color(*self.accent_color)
            self.set_line_width(0.8)
            
            for i in range(len(hr_data) - 1):
                x1 = graph_x + (i / (len(hr_data) - 1)) * graph_width
                x2 = graph_x + ((i + 1) / (len(hr_data) - 1)) * graph_width
                y1 = graph_y + graph_height - ((hr_data[i] - hr_min) / (hr_max - hr_min)) * (graph_height - 10) - 5
                y2 = graph_y + graph_height - ((hr_data[i + 1] - hr_min) / (hr_max - hr_min)) * (graph_height - 10) - 5
                self.line(x1, y1, x2, y2)
        
        if len(spo2_data) >= 2:
            spo2_min, spo2_max = min(spo2_data), max(spo2_data)
            if spo2_max == spo2_min:
                spo2_max = spo2_min + 1
            
            # Draw SpO2 line (blue)
            self.set_draw_color(52, 152, 219)
            self.set_line_width(0.8)
            
            for i in range(len(spo2_data) - 1):
                x1 = graph_x + (i / (len(spo2_data) - 1)) * graph_width
                x2 = graph_x + ((i + 1) / (len(spo2_data) - 1)) * graph_width
                y1 = graph_y + graph_height - ((spo2_data[i] - spo2_min) / (spo2_max - spo2_min)) * (graph_height - 10) - 5
                y2 = graph_y + graph_height - ((spo2_data[i + 1] - spo2_min) / (spo2_max - spo2_min)) * (graph_height - 10) - 5
                self.line(x1, y1, x2, y2)
        
        # Legend
        self.set_y(graph_y + graph_height + 3)
        self.set_font('Helvetica', '', 8)
        self.set_text_color(*self.accent_color)
        self.cell(10, 5, '', 0, 0)
        self.cell(5, 5, '', 0, 0)
        self.set_draw_color(*self.accent_color)
        self.line(self.get_x(), self.get_y() + 2.5, self.get_x() + 15, self.get_y() + 2.5)
        self.cell(20, 5, '', 0, 0)
        self.set_text_color(*self.text_color)
        self.cell(30, 5, 'Heart Rate (BPM)', 0, 0, 'L')
        
        self.set_draw_color(52, 152, 219)
        self.line(self.get_x() + 5, self.get_y() + 2.5, self.get_x() + 20, self.get_y() + 2.5)
        self.cell(25, 5, '', 0, 0)
        self.set_text_color(52, 152, 219)
        self.cell(30, 5, 'SpO2 (%)', 0, 1, 'L')
        
        self.ln(8)
        
    def add_ai_observations(self, ai_message):
        self.section_title('AI CLINICAL OBSERVATIONS')
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*self.text_color)
        self.multi_cell(0, 6, ai_message, 0, 'L')
        self.ln(5)
        
    def add_prescription_section(self):
        self.section_title('PHYSICIAN ORDERS / PRESCRIPTION')
        
        # Draw large bordered area with dotted lines
        box_x = 10
        box_y = self.get_y()
        box_width = 190
        box_height = 55
        
        self.set_draw_color(150, 150, 150)
        self.set_line_width(0.3)
        self.rect(box_x, box_y, box_width, box_height)
        
        # Draw dotted lines for writing
        self.set_draw_color(200, 200, 200)
        line_spacing = 9
        for i in range(1, 6):
            y_line = box_y + (line_spacing * i)
            # Draw dashed line
            x = box_x + 5
            while x < box_x + box_width - 5:
                self.line(x, y_line, min(x + 3, box_x + box_width - 5), y_line)
                x += 6
        
        self.set_y(box_y + box_height + 5)


def create_clinical_report_pdf(vitals_data, ai_message, hr_history, spo2_history):
    """Generate a professional clinical report PDF"""
    if not FPDF_AVAILABLE:
        return None
    
    pdf = ClinicalReportPDF()
    pdf.add_page()
    
    # Add vitals table
    pdf.add_vitals_table(vitals_data)
    
    # Add trend graph
    pdf.add_vitals_graph(hr_history, spo2_history)
    
    # Add AI observations
    pdf.add_ai_observations(ai_message)
    
    # Add prescription section
    pdf.add_prescription_section()
    
    # Return PDF as bytes
    return pdf.output(dest='S').encode('latin-1')

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="ICU Guardian Command Center",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CUSTOM CSS: INTENTIONAL COMMAND-CENTER LOOK ---
st.markdown("""
<style>
    /* ==================== GLOBAL ==================== */
    @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap');

    .stApp {
        background: radial-gradient(circle at 20% 20%, rgba(0, 173, 181, 0.08), transparent 25%),
                    radial-gradient(circle at 80% 10%, rgba(255, 71, 87, 0.08), transparent 22%),
                    linear-gradient(140deg, #040712 0%, #0b1024 45%, #050915 100%);
        color: #E9ECF5;
        font-family: 'Space Grotesk', 'SF Pro Display', 'Segoe UI', sans-serif;
    }

    .block-container {padding-top: 1.5rem;}

    /* ==================== GLASS + GRID CARDS ==================== */
    .glass-card {
        background: rgba(15, 18, 35, 0.82);
        backdrop-filter: blur(18px);
        border: 1px solid rgba(0, 255, 213, 0.12);
        border-radius: 18px;
        padding: 22px;
        box-shadow: 0 18px 50px rgba(0, 0, 0, 0.45), inset 0 1px 0 rgba(255, 255, 255, 0.04);
        position: relative;
        overflow: hidden;
    }

    .glass-card::after {
        content: "";
        position: absolute;
        inset: 0;
        background: linear-gradient(135deg, rgba(0, 173, 181, 0.14), transparent 45%);
        opacity: 0;
        transition: opacity 0.25s ease;
        pointer-events: none;
    }

    .glass-card:hover::after {opacity: 1;}
    .glass-card:hover {transform: translateY(-3px); transition: transform 0.25s ease;}

    /* ==================== METRICS ==================== */
    div[data-testid="metric-container"] {
        background: linear-gradient(120deg, rgba(16, 21, 38, 0.95) 0%, rgba(18, 24, 52, 0.9) 100%);
        border: 1px solid rgba(0, 255, 213, 0.18);
        padding: 20px 18px;
        border-radius: 16px;
        box-shadow: 0 6px 30px rgba(0, 0, 0, 0.32);
    }

    div[data-testid="stMetricValue"] {
        font-size: 2.35rem;
        font-weight: 700;
        background: linear-gradient(120deg, #4df3c9 0%, #00b7ff 45%, #0077ff 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
        letter-spacing: -0.5px;
    }

    div[data-testid="stMetricLabel"] {
        color: #9ca8c9;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 1px;
        font-size: 0.74rem;
    }

    /* ==================== TYPOGRAPHY ==================== */
    h1, h2, h3 { letter-spacing: -0.02em; }
    h1 { color: #e4f2ff; font-weight: 700; margin-bottom: 0; }
    h2 { color: #7ddaff; font-weight: 600; }
    h3 { color: #8da1c7; font-weight: 600; }

    /* ==================== BUTTONS ==================== */
    .stButton>button {
        background: linear-gradient(130deg, #00f2c3 0%, #00a2ff 100%);
        color: #03111f;
        border: 0;
        border-radius: 12px;
        padding: 14px 24px;
        font-weight: 700;
        letter-spacing: -0.01em;
        box-shadow: 0 10px 30px rgba(0, 200, 255, 0.35);
        transition: transform 0.2s ease, box-shadow 0.2s ease;
    }

    .stButton>button:hover {transform: translateY(-2px); box-shadow: 0 16px 38px rgba(0, 200, 255, 0.45);}

    /* ==================== ALERT CARDS ==================== */
    .alert-card {
        background: linear-gradient(115deg, rgba(18, 22, 40, 0.92), rgba(10, 14, 30, 0.92));
        border-left: 4px solid;
        padding: 14px 18px;
        margin: 10px 0;
        border-radius: 12px;
        box-shadow: 0 10px 26px rgba(0, 0, 0, 0.35);
    }

    .alert-critical { border-left-color: #ff4d6d; }
    .alert-warning { border-left-color: #ffb347; }
    .alert-info { border-left-color: #4dd4ff; }
    .alert-success { border-left-color: #37e599; }

    /* ==================== STATUS BADGES ==================== */
    .status-badge {
        display: inline-flex;
        align-items: center;
        gap: 8px;
        padding: 7px 14px;
        border-radius: 999px;
        font-weight: 700;
        font-size: 0.82rem;
        letter-spacing: 0.02em;
    }

    .status-active {background: linear-gradient(125deg, #37e599 0%, #0fce7b 100%); color: #00150c; box-shadow: 0 0 16px rgba(55, 229, 153, 0.45);}
    .status-inactive {background: rgba(103, 120, 151, 0.22); color: #9aa8c1;}
    .status-critical {background: linear-gradient(125deg, #ff4d6d 0%, #d9003a 100%); color: #ffe6ed; box-shadow: 0 0 18px rgba(255, 77, 109, 0.45);}
    .status-warning {background: linear-gradient(125deg, #ffb347 0%, #ff7a18 100%); color: #2b0c00; box-shadow: 0 0 14px rgba(255, 179, 71, 0.35);}

    /* ==================== TABS ==================== */
    .stTabs [data-baseweb="tab-list"] {
        gap: 10px;
        background: rgba(16, 21, 38, 0.7);
        border-radius: 12px;
        padding: 10px;
        border: 1px solid rgba(0, 255, 213, 0.1);
    }

    .stTabs [data-baseweb="tab"] {color: #9fb0d1; font-weight: 600; padding: 10px 18px;}
    .stTabs [aria-selected="true"] {background: linear-gradient(125deg, #00f2c3 0%, #00a2ff 100%); color: #03111f; border-radius: 10px;}

    /* ==================== SCROLLBAR ==================== */
    ::-webkit-scrollbar {width: 10px; height: 10px;}
    ::-webkit-scrollbar-track {background: rgba(12, 16, 30, 0.7); border-radius: 10px;}
    ::-webkit-scrollbar-thumb {background: linear-gradient(135deg, #00f2c3 0%, #00a2ff 100%); border-radius: 10px;}

    /* ==================== MONITOR LINE ==================== */
    .monitor-line {height: 2px; background: linear-gradient(90deg, transparent, #00f2c3, transparent); animation: scan 2s linear infinite;}
    @keyframes scan {0% {transform: translateX(-100%);} 100% {transform: translateX(100%);} }

    /* ==================== HERO RIBBON ==================== */
    .ops-ribbon {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
        gap: 10px;
        margin-top: 14px;
    }

    .ops-chip {
        background: rgba(255, 255, 255, 0.04);
        border: 1px solid rgba(0, 255, 213, 0.12);
        padding: 10px 14px;
        border-radius: 12px;
        color: #b9c7e3;
        font-weight: 600;
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .ops-chip span {color: #6ddcff; font-weight: 700;}
</style>
""", unsafe_allow_html=True)

# --- SESSION STATE INITIALIZATION ---
if "vision_process" not in st.session_state:
    st.session_state.vision_process = None
if "alert_history" not in st.session_state:
    st.session_state.alert_history = []
if "pillar_status" not in st.session_state:
    st.session_state.pillar_status = {
        "self_harm": {"active": False, "last_alert": None, "count": 0},
        "agitation": {"active": False, "last_alert": None, "count": 0},
        "distress": {"active": False, "last_alert": None, "count": 0},
        "fall": {"active": False, "last_alert": None, "count": 0}
    }
if "vital_data" not in st.session_state:
    st.session_state.vital_data = pd.DataFrame(columns=["HR", "SpO2", "Time", "Timestamp"])
if "system_start_time" not in st.session_state:
    st.session_state.system_start_time = datetime.now()
if "total_patients_monitored" not in st.session_state:
    st.session_state.total_patients_monitored = 1

# --- VISION SYSTEM CONTROL FUNCTIONS ---
def start_vision_system():
    """Launch the vision monitoring subprocess"""
    if st.session_state.vision_process is None or not is_vision_running():
        python_path = Path(sys.executable)
        script_path = Path("pillars/self_harm.py").resolve()
        
        import os
        env = os.environ.copy()
        env['PYTHONPATH'] = str(Path(__file__).parent.resolve())
        
        st.session_state.vision_process = subprocess.Popen(
            [str(python_path), str(script_path)],
            cwd=str(Path(__file__).parent),
            env=env,
            creationflags=subprocess.CREATE_NEW_CONSOLE if sys.platform == 'win32' else 0
        )
        add_alert("SYSTEM", "Vision Guardian activated", "success")
        return True
    return False

def stop_vision_system():
    """Terminate the vision monitoring subprocess"""
    if st.session_state.vision_process and is_vision_running():
        try:
            parent = psutil.Process(st.session_state.vision_process.pid)
            for child in parent.children(recursive=True):
                child.terminate()
            parent.terminate()
            parent.wait(timeout=5)
        except:
            pass
        st.session_state.vision_process = None
        add_alert("SYSTEM", "Vision Guardian deactivated", "info")
        return True
    return False

def is_vision_running():
    """Check if vision system process is active"""
    if st.session_state.vision_process:
        try:
            return psutil.pid_exists(st.session_state.vision_process.pid)
        except:
            return False
    return False

def add_alert(pillar, message, severity="warning"):
    """Add alert to history feed"""
    alert = {
        "timestamp": datetime.now().strftime("%H:%M:%S"),
        "pillar": pillar,
        "message": message,
        "severity": severity
    }
    st.session_state.alert_history.insert(0, alert)
    if len(st.session_state.alert_history) > 100:
        st.session_state.alert_history = st.session_state.alert_history[:100]

def update_pillar_status_from_file():
    """Read alert status from shared JSON file and update dashboard state"""
    try:
        if STATUS_FILE.exists():
            with open(STATUS_FILE, 'r') as f:
                data = json.load(f)
            
            if "pillars" in data:
                for pillar_name, pillar_data in data["pillars"].items():
                    if pillar_name in st.session_state.pillar_status:
                        # Update the pillar status
                        st.session_state.pillar_status[pillar_name]["active"] = pillar_data.get("active", False)
                        st.session_state.pillar_status[pillar_name]["count"] = pillar_data.get("count", 0)
                        
                        # Update last alert time if available
                        if pillar_data.get("last_alert"):
                            st.session_state.pillar_status[pillar_name]["last_alert"] = pillar_data["last_alert"]
                        
                        # Add to alert history if newly active
                        if pillar_data.get("active") and pillar_data.get("elapsed_seconds", 0) < 2:
                            elapsed = pillar_data.get("elapsed_seconds", 0)
                            add_alert(
                                pillar_name.upper(),
                                f"Alert detected - {elapsed:.1f}s elapsed",
                                "critical" if pillar_name in ["self_harm", "fall"] else "warning"
                            )
                
                return True
    except Exception as e:
        # Silently handle file read errors
        pass
    return False

# --- LOAD AI MODEL ---
@st.cache_resource
def get_model():
    return load_trained_model()

model = get_model()
scaler = MinMaxScaler()
scaler.fit([[50, 80, 0, -5], [150, 100, 5, 4]])

# --- AI DOCTOR ANALYSIS ---
def get_ai_analysis(vitals, risk_prob):
    """AI-powered patient analysis"""
    hr = vitals['HR_Avg']
    spo2 = vitals['SpO2_Min']
    rass = vitals['RASS_Score']
    sleep = vitals['Sleep_Score']
    
    if risk_prob > 0.6:
        return {
            "severity": "critical",
            "icon": "🚨",
            "title": "CRITICAL: IMMEDIATE INTERVENTION REQUIRED",
            "message": f"Acute delirium risk ({risk_prob:.0%}). Patient showing signs of severe agitation (RASS: {rass}). HR elevated at {hr} BPM.",
            "actions": [
                "Administer prescribed sedation protocol",
                "Check pain levels and provide analgesia",
                f"Assess oxygen delivery (SpO2: {spo2}%)",
                "Activate Vision Guardian for 24/7 monitoring",
                "Notify attending physician immediately"
            ]
        }
    elif risk_prob > 0.4:
        return {
            "severity": "warning",
            "icon": "⚠️",
            "title": "WARNING: ELEVATED DELIRIUM RISK",
            "message": f"Patient showing early signs of delirium ({risk_prob:.0%}). HR: {hr} BPM, Sleep quality compromised ({sleep}/5).",
            "actions": [
                "Increase monitoring frequency",
                "Assess environmental factors (noise, lighting)",
                "Review medication list for deliriogenic drugs",
                "Implement non-pharmacological interventions",
                "Continue Vision Guardian surveillance"
            ]
        }
    elif spo2 < 92:
        return {
            "severity": "warning",
            "icon": "🫁",
            "title": "ALERT: HYPOXIA DETECTED",
            "message": f"Oxygen saturation critically low (SpO2: {spo2}%). Immediate respiratory assessment required.",
            "actions": [
                "Check oxygen delivery system",
                "Reposition patient (semi-Fowler's position)",
                "Assess respiratory rate and effort",
                "Consider arterial blood gas analysis",
                "Alert respiratory therapy team"
            ]
        }
    elif hr > 100:
        return {
            "severity": "warning",
            "icon": "💓",
            "title": "ALERT: TACHYCARDIA DETECTED",
            "message": f"Heart rate elevated ({hr} BPM). Patient may be experiencing pain, anxiety, or physiological stress.",
            "actions": [
                "Assess pain levels using validated scale",
                "Check for signs of infection (fever, WBC)",
                "Review fluid balance and hydration status",
                "Monitor for cardiac arrhythmias",
                "Consider ECG if persistent"
            ]
        }
    else:
        return {
            "severity": "success",
            "icon": "✅",
            "title": "STATUS: PATIENT STABLE",
            "message": f"All vitals within normal limits. HR: {hr} BPM, SpO2: {spo2}%, Sleep: {sleep}/5, RASS: {rass}.",
            "actions": [
                "Continue current care plan",
                "Maintain routine monitoring intervals",
                "Encourage early mobilization when appropriate",
                "Optimize sleep-wake cycle",
                "Document stable status in medical record"
            ]
        }

# ============================================
# SIDEBAR: SYSTEM CONTROL PANEL
# ============================================
with st.sidebar:
    st.markdown('<div style="text-align: center; margin-bottom: 20px;">', unsafe_allow_html=True)
    st.markdown("🏥")
    st.markdown('</div>', unsafe_allow_html=True)
    
    st.markdown("# ICU GUARDIAN")
    st.markdown('<p style="text-align: center; color: #7F8C8D; font-size: 0.9rem; margin-top: -10px;">Command Center v2.0</p>', unsafe_allow_html=True)
    st.markdown("---")
    
    # System Status Overview
    uptime = datetime.now() - st.session_state.system_start_time
    hours, remainder = divmod(int(uptime.total_seconds()), 3600)
    minutes, seconds = divmod(remainder, 60)
    
    st.markdown("### 📊 System Status")
    col1, col2 = st.columns(2)
    with col1:
        st.metric("Uptime", f"{hours:02d}:{minutes:02d}:{seconds:02d}")
    with col2:
        st.metric("Patients", st.session_state.total_patients_monitored)
    
    total_alerts = sum(p["count"] for p in st.session_state.pillar_status.values())
    st.metric("Total Alerts", total_alerts)
    
    st.markdown("---")
    
    # Vision System Controls
    st.markdown("### 📷 Vision System")
    vision_running = is_vision_running()
    
    if vision_running:
        st.markdown('<span class="status-badge status-active">● ACTIVE</span>', unsafe_allow_html=True)
        if st.button("🛑 Stop Vision System", use_container_width=True, type="secondary"):
            stop_vision_system()
            st.rerun()
    else:
        st.markdown('<span class="status-badge status-inactive">○ INACTIVE</span>', unsafe_allow_html=True)
        if st.button("▶️ Launch Vision System", use_container_width=True, type="primary"):
            start_vision_system()
            st.rerun()

    # Keep pillar status fresh even when live monitoring toggle is off
    if vision_running:
        update_pillar_status_from_file()
    
    st.markdown("---")
    
    # Pillar Status Panel
    st.markdown("### 🛡️ Detection Pillars")
    
    pillar_icons = {
        "self_harm": "🚨",
        "agitation": "🌊",
        "distress": "😰",
        "fall": "⚠️"
    }
    
    for pillar, data in st.session_state.pillar_status.items():
        status_class = "status-active" if data["active"] else "status-inactive"
        icon = pillar_icons.get(pillar, "⚪")
        pillar_name = pillar.replace("_", " ").title()
        
        st.markdown(f"""
        <div style="
            background: rgba(30, 33, 48, 0.5);
            padding: 12px;
            border-radius: 8px;
            margin-bottom: 8px;
            border-left: 3px solid {'#2ECC71' if data['active'] else '#95A5A6'};
        ">
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <span style="font-weight: 600;">{icon} {pillar_name}</span>
                <span style="font-size: 0.85rem; color: #A0AEC0;">{data['count']} alerts</span>
            </div>
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("---")
    
    # Quick Actions
    st.markdown("### ⚡ Quick Actions")
    if st.button("🔄 Reset Alerts", use_container_width=True):
        st.session_state.alert_history = []
        for pillar in st.session_state.pillar_status:
            st.session_state.pillar_status[pillar]["count"] = 0
        st.toast("All alerts cleared!", icon="✅")
        st.rerun()
    
    # Generate Clinical Report PDF
    if FPDF_AVAILABLE:
        st.markdown("---")
        st.markdown("### 📋 Clinical Report")
        
        # Gather data for PDF
        if not st.session_state.vital_data.empty:
            hr_history = st.session_state.vital_data['HR'].tail(10).tolist()
            spo2_history = st.session_state.vital_data['SpO2'].tail(10).tolist()
            latest_hr = st.session_state.vital_data['HR'].iloc[-1] if len(st.session_state.vital_data) > 0 else 72
            latest_spo2 = st.session_state.vital_data['SpO2'].iloc[-1] if len(st.session_state.vital_data) > 0 else 98
        else:
            hr_history = [72, 75, 73, 78, 76, 74, 77, 75, 73, 74]
            spo2_history = [98, 97, 98, 97, 96, 98, 97, 98, 97, 98]
            latest_hr = 74
            latest_spo2 = 98
        
        # Get AI message from session or generate default
        ai_message = "Patient vitals within normal parameters. Continuous monitoring recommended. No immediate intervention required."
        if st.session_state.alert_history:
            latest_alert = st.session_state.alert_history[0]
            ai_message = f"Latest Alert: {latest_alert['pillar']} - {latest_alert['message']} at {latest_alert['timestamp']}. Continue monitoring and assess patient condition."
        
        vitals_data = {
            'hr': int(latest_hr),
            'spo2': int(latest_spo2),
            'rass': 0,
            'risk': 0.15
        }
        
        pdf_bytes = create_clinical_report_pdf(vitals_data, ai_message, hr_history, spo2_history)
        
        if pdf_bytes:
            report_date = datetime.now().strftime('%Y%m%d_%H%M')
            st.download_button(
                label="📄 Download Clinical Report",
                data=pdf_bytes,
                file_name=f"ICU_Report_{report_date}.pdf",
                mime="application/pdf",
                use_container_width=True
            )
        else:
            st.warning("PDF generation unavailable")
    else:
        st.caption("Install 'fpdf' for PDF reports")
    
    st.markdown("---")
    st.caption("🔒 AI-Powered Patient Monitoring")
    st.caption(f"© 2026 ICU Guardian")
    st.caption(f"Session: {datetime.now().strftime('%Y-%m-%d %H:%M')}")

# ============================================
# MAIN DASHBOARD LAYOUT
# ============================================

# Header with animated title
vision_running_main = is_vision_running()
uptime_delta = datetime.now() - st.session_state.system_start_time
h, remainder = divmod(int(uptime_delta.total_seconds()), 3600)
m, s = divmod(remainder, 60)
uptime_str = f"{h:02d}:{m:02d}:{s:02d}"

total_alerts = sum(p["count"] for p in st.session_state.pillar_status.values())
last_alert = st.session_state.alert_history[0]["timestamp"] if st.session_state.alert_history else "No alerts yet"

hero_html = f"""
<div class="glass-card" style="padding: 24px; margin-bottom: 18px; border: 1px solid rgba(0, 255, 213, 0.16);">
  <div style="display: flex; gap: 18px; align-items: center; justify-content: space-between; flex-wrap: wrap;">
    <div style="flex: 1; min-width: 320px;">
      <div style="color: #6ddcff; font-weight: 700; letter-spacing: 0.14em; font-size: 0.75rem; text-transform: uppercase;">ICU Guardian · Command Center</div>
      <h1 style="font-size: 2.7rem; margin: 6px 0 8px 0;">Live Ops & Clinical AI</h1>
      <p style="color: #97a6c9; max-width: 640px; font-size: 1.02rem;">Continuous bedside vision, real-time vitals, and AI-driven decision support aligned into a single control surface built for rapid response.</p>
      <div class="ops-ribbon">
        <div class="ops-chip">Uptime <span>{uptime_str}</span></div>
        <div class="ops-chip">Alerts <span>{total_alerts}</span></div>
        <div class="ops-chip">Patients <span>{st.session_state.total_patients_monitored}</span></div>
        <div class="ops-chip">Last alert <span>{last_alert}</span></div>
      </div>
    </div>
    <div style="min-width: 240px; text-align: right; display: grid; gap: 10px;">
      <div>{'<span class="status-badge status-active">🟢 Vision Online</span>' if vision_running_main else '<span class="status-badge status-inactive">⚪ Vision Offline</span>'}</div>
      <div style="color: #8ea4cd; font-size: 0.95rem;">Clinical AI and video sentry run in parallel; alerts sync to the dashboard every heartbeat.</div>
    </div>
  </div>
  <div class="monitor-line" style="margin-top: 18px;"></div>
</div>
"""

st.markdown(hero_html, unsafe_allow_html=True)

# Top Metrics Row
col1, col2, col3, col4 = st.columns(4)
with col1:
    hr_metric = st.empty()
with col2:
    spo2_metric = st.empty()
with col3:
    sleep_metric = st.empty()
with col4:
    status_metric = st.empty()

st.markdown("<div style='height: 6px;'></div>", unsafe_allow_html=True)

# Main Content Tabs
tab1, tab2, tab3 = st.tabs(["📊 Live Monitoring", "🤖 AI Doctor", "📈 Analytics"])

with tab1:
    col_charts, col_alerts = st.columns([2, 1])
    
    with col_charts:
        st.markdown("### 📊 Live Vitals Monitoring")
        
        chart_container = st.container()
        with chart_container:
            chart_tabs = st.tabs(["Heart Rate", "Oxygen Saturation", "Trends"])
            
            with chart_tabs[0]:
                hr_chart = st.empty()
            with chart_tabs[1]:
                spo2_chart = st.empty()
            with chart_tabs[2]:
                trends_chart = st.empty()
    
    with col_alerts:
        st.markdown("### 🚨 Alert History Feed")
        alert_container = st.container(height=600)
        
        with alert_container:
            if len(st.session_state.alert_history) == 0:
                st.info("✅ No alerts recorded. System ready.", icon="ℹ️")
            else:
                for alert in st.session_state.alert_history[:15]:
                    severity_config = {
                        "critical": {"color": "#FF4757", "icon": "🔴"},
                        "warning": {"color": "#FFA502", "icon": "🟡"},
                        "info": {"color": "#00ADB5", "icon": "🔵"},
                        "success": {"color": "#2ECC71", "icon": "🟢"}
                    }
                    
                    config = severity_config.get(alert["severity"], severity_config["info"])
                    
                    st.markdown(f"""
                    <div class="alert-card alert-{alert['severity']}">
                        <div style="display: flex; align-items: start; gap: 12px;">
                            <span style="font-size: 1.5rem;">{config['icon']}</span>
                            <div style="flex: 1;">
                                <strong style="color: {config['color']}; font-size: 0.95rem;">{alert['pillar'].upper()}</strong>
                                <p style="margin: 4px 0; font-size: 0.9rem; color: #E8EAED;">{alert['message']}</p>
                                <small style="color: #7F8C8D;">{alert['timestamp']}</small>
                            </div>
                        </div>
                    </div>
                    """, unsafe_allow_html=True)

with tab2:
    st.markdown("### 🤖 Dr. AI Clinical Insights")
    ai_insights_container = st.empty()
    
    st.markdown("### 📋 Clinical Decision Support")
    col_actions1, col_actions2 = st.columns(2)
    
    with col_actions1:
        st.markdown("#### 🎯 Recommended Interventions")
        interventions_placeholder = st.empty()
    
    with col_actions2:
        st.markdown("#### 📊 Risk Assessment")
        risk_placeholder = st.empty()

with tab3:
    st.markdown("### 📈 Advanced Analytics & Trends")
    
    col_stats1, col_stats2, col_stats3 = st.columns(3)
    
    with col_stats1:
        st.markdown("#### 📊 Vital Statistics")
        stats_placeholder1 = st.empty()
    
    with col_stats2:
        st.markdown("#### ⚠️ Alert Distribution")
        stats_placeholder2 = st.empty()
    
    with col_stats3:
        st.markdown("#### 🎯 System Performance")
        stats_placeholder3 = st.empty()

st.markdown("---")

# Monitoring Control
monitoring_col1, monitoring_col2 = st.columns([3, 1])

with monitoring_col1:
    monitoring = st.checkbox(
        "▶️ **ACTIVATE LIVE MONITORING**", 
        value=False,
        help="Start continuous patient monitoring and AI analysis"
    )

st.session_state["monitoring_active"] = monitoring

"""Auto-refresh pillar counts when vision is running but live monitoring toggle is off."""
vision_running = is_vision_running()
if vision_running and not monitoring:
    last = st.session_state.get("vision_autorefresh_ts", 0)
    now = time.time()
    if now - last > 1.5:
        st.session_state["vision_autorefresh_ts"] = now
        update_pillar_status_from_file()
        st.experimental_rerun()
    else:
        update_pillar_status_from_file()

with monitoring_col2:
    if monitoring:
        st.markdown('<span class="status-badge status-active">🟢 MONITORING ACTIVE</span>', unsafe_allow_html=True)
    else:
        st.markdown('<span class="status-badge status-inactive">⚪ STANDBY</span>', unsafe_allow_html=True)

# ============================================
# LIVE MONITORING LOOP
# ============================================
if monitoring:
    while monitoring:
        # Update pillar status from vision system
        update_pillar_status_from_file()
        
        # Generate patient data and predict
        vitals = generate_patient_data()
        input_scaled = scaler.transform(np.array([[
            vitals['HR_Avg'], vitals['SpO2_Min'],
            vitals['Sleep_Score'], vitals['RASS_Score']
        ]]))
        prediction, probability = predict_psychosis(model, input_scaled)
        
        # Update metrics
        if prediction == 1:
            status_metric.markdown('<span class="status-badge status-critical">🔴 CRITICAL RISK</span>', unsafe_allow_html=True)
            add_alert("PSYCHOSIS AI", f"High delirium risk detected ({probability:.0%})", "critical")
        elif probability > 0.4:
            status_metric.markdown('<span class="status-badge status-warning">🟡 WARNING</span>', unsafe_allow_html=True)
        else:
            status_metric.markdown('<span class="status-badge status-active">🟢 STABLE</span>', unsafe_allow_html=True)
        
        hr_metric.metric("💓 Heart Rate", f"{vitals['HR_Avg']}", "BPM")
        spo2_metric.metric("🫁 SpO2", f"{vitals['SpO2_Min']}", "%")
        sleep_metric.metric("😴 Sleep Score", f"{vitals['Sleep_Score']}", "/5")
        
        # Update AI analysis
        ai_analysis = get_ai_analysis(vitals, probability)
        
        with ai_insights_container.container():
            severity_colors = {
                "critical": "#FF4757",
                "warning": "#FFA502",
                "success": "#2ECC71"
            }
            
            color = severity_colors.get(ai_analysis["severity"], "#00ADB5")
            
            st.markdown(f"""
            <div class="glass-card" style="border-left: 4px solid {color};">
                <div style="display: flex; align-items: center; gap: 12px; margin-bottom: 12px;">
                    <span style="font-size: 2rem;">{ai_analysis["icon"]}</span>
                    <h3 style="color: {color}; margin: 0;">{ai_analysis["title"]}</h3>
                </div>
                <p style="font-size: 1.05rem; margin-bottom: 16px; color: #E8EAED;">{ai_analysis["message"]}</p>
                <div style="background: rgba(0,0,0,0.2); padding: 12px; border-radius: 8px;">
                    <strong style="color: #00D9FF;">Clinical Actions:</strong>
                    <ul style="margin-top: 8px; color: #A0AEC0;">
                        {"".join([f"<li>{action}</li>" for action in ai_analysis["actions"]])}
                    </ul>
                </div>
            </div>
            """, unsafe_allow_html=True)
        
        # Update interventions and risk assessment
        with interventions_placeholder.container():
            for i, action in enumerate(ai_analysis["actions"][:3], 1):
                st.markdown(f"**{i}.** {action}")
        
        with risk_placeholder.container():
            risk_level = "High" if probability > 0.6 else "Moderate" if probability > 0.4 else "Low"
            risk_color = "#FF4757" if probability > 0.6 else "#FFA502" if probability > 0.4 else "#2ECC71"
            
            st.markdown(f"""
            <div style="text-align: center; padding: 20px;">
                <div style="font-size: 3rem; font-weight: 700; color: {risk_color};">
                    {probability:.0%}
                </div>
                <div style="color: #A0AEC0; margin-top: 8px;">
                    {risk_level} Risk
                </div>
            </div>
            """, unsafe_allow_html=True)
            
            st.progress(probability)
        
        # Update analytics
        if len(st.session_state.vital_data) > 0:
            with stats_placeholder1.container():
                avg_hr = st.session_state.vital_data["HR"].mean()
                avg_spo2 = st.session_state.vital_data["SpO2"].mean()
                st.metric("Avg HR", f"{avg_hr:.1f} BPM")
                st.metric("Avg SpO2", f"{avg_spo2:.1f}%")
            
            with stats_placeholder2.container():
                total = sum(p["count"] for p in st.session_state.pillar_status.values())
                if total > 0:
                    for pillar, data in list(st.session_state.pillar_status.items())[:3]:
                        percentage = (data["count"] / total) * 100
                        st.metric(pillar.replace("_", " ").title(), f"{percentage:.1f}%")
            
            with stats_placeholder3.container():
                uptime_seconds = (datetime.now() - st.session_state.system_start_time).total_seconds()
                readings = len(st.session_state.vital_data)
                rate = readings / (uptime_seconds / 60) if uptime_seconds > 0 else 0
                st.metric("Data Rate", f"{rate:.1f}/min")
                st.metric("Total Readings", readings)
        
        # Update data and charts
        current_time = time.time()
        new_row = {
            "HR": vitals['HR_Avg'], 
            "SpO2": vitals['SpO2_Min'], 
            "Time": current_time,
            "Timestamp": datetime.now()
        }
        st.session_state.vital_data = pd.concat(
            [st.session_state.vital_data, pd.DataFrame([new_row])],
            ignore_index=True
        )
        
        if len(st.session_state.vital_data) > 120:
            st.session_state.vital_data = st.session_state.vital_data.iloc[-120:]
        
        # Simple matplotlib-style charts
        with chart_tabs[0]:
            hr_chart.line_chart(st.session_state.vital_data.set_index('Time')['HR'], color='#FF4757')
        
        with chart_tabs[1]:
            spo2_chart.line_chart(st.session_state.vital_data.set_index('Time')['SpO2'], color='#00D9FF')
        
        with chart_tabs[2]:
            trends_chart.line_chart(st.session_state.vital_data.set_index('Time')[['HR', 'SpO2']])
        
        time.sleep(1.5)
        st.rerun()
